In [19]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import numpy as np
import tensorflow as tf
import csv

from matplotlib.image import imread
import matplotlib.pyplot as plt
from sklearn import svm, metrics


In [10]:
import csv

with open("pac_transform_guide.csv") as csv_file:
    reader = csv.reader(csv_file)
    i = 0
    image_paths = []
    im_labels = []
    
    for ind, row in enumerate(reader):
        index = row[0]
        filename = row[1]
        label = row[2]
        image_paths.append(filename)
        im_labels.append(label)

In [23]:
files = ['08', '11', '15']


In [37]:
file = files[0]

train_indices = np.load("pac_augment_arrays/ocean_train_inds_" + str(file) + ".npy")
test_indices = np.load("pac_augment_arrays/ocean_test_inds_" + str(file) + ".npy")

data_hog_features = np.load("pac_hog_features_" + str(file) + ".npy")
print(train_indices.shape)
print(test_indices.shape)
print(data_hog_features.shape)

train_len = len(train_indices)
test_len = len(test_indices)
features_train = data_hog_features[:train_len]
features_test = data_hog_features[train_len:train_len+test_len]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]

num_0 = 0
num_1 = 1
for i in labels_train:
    if i == '0':
        num_0 += 1
    if i == '1':
        num_1 += 1
ratio = num_0 / num_1
print('ratio: ' + str(ratio))

class_weight = {'0' : 1.,
    '1': ratio}

classifier = svm.SVC(gamma=0.001, class_weight = class_weight)

classifier.fit(features_train, labels_train)

predictions = classifier.predict(features_test)

print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

(1980,)
(660,)
(2640, 200)
ratio: 8.213953488372093
Classification report:
             precision    recall  f1-score   support

          0       0.90      1.00      0.95       594
          1       0.00      0.00      0.00        66

avg / total       0.81      0.90      0.85       660


Confusion matrix:
[[594   0]
 [ 66   0]]


/Users/Edward_Chou/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
file = files[1]

train_indices = np.load("pac_augment_arrays/ocean_train_inds_" + str(file) + ".npy")
test_indices = np.load("pac_augment_arrays/ocean_test_inds_" + str(file) + ".npy")

data_hog_features = np.load("pac_hog_features_" + str(file) + ".npy")
print(train_indices.shape)
print(test_indices.shape)
print(data_hog_features.shape)

train_len = len(train_indices)
test_len = len(test_indices)
features_train = data_hog_features[:train_len]
features_test = data_hog_features[train_len:train_len+test_len]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]


num_0 = 0
num_1 = 1
for i in labels_train:
    if i == '0':
        num_0 += 1
    if i == '1':
        num_1 += 1
ratio = num_0 / num_1
print('ratio: ' + str(ratio))

class_weight = {'0' : 1.,
    '1': ratio}

classifier = svm.SVC(gamma=0.001, class_weight = class_weight)
classifier.fit(features_train, labels_train)

predictions = classifier.predict(features_test)

print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

(1980,)
(660,)
(2640, 200)
ratio: 19.214285714285715
Classification report:
             precision    recall  f1-score   support

          0       0.96      1.00      0.98       635
          1       0.00      0.00      0.00        25

avg / total       0.93      0.96      0.94       660


Confusion matrix:
[[635   0]
 [ 25   0]]


/Users/Edward_Chou/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [35]:
file = files[2]

train_indices = np.load("pac_augment_arrays/ocean_train_inds_" + str(file) + ".npy")
test_indices = np.load("pac_augment_arrays/ocean_test_inds_" + str(file) + ".npy")

data_hog_features = np.load("pac_hog_features_" + str(file) + ".npy")
print(train_indices.shape)
print(test_indices.shape)
print(data_hog_features.shape)

train_len = len(train_indices)
test_len = len(test_indices)
features_train = data_hog_features[:train_len]
features_test = data_hog_features[train_len:train_len+test_len]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]


num_0 = 0
num_1 = 1
for i in labels_train:
    if i == '0':
        num_0 += 1
    if i == '1':
        num_1 += 1
ratio = num_0 / num_1
print('ratio: ' + str(ratio))

class_weight = {'0' : 1.,
    '1': ratio}

classifier = svm.SVC(gamma=0.001, class_weight = class_weight)
classifier.fit(features_train, labels_train)

predictions = classifier.predict(features_test)

print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

(1980,)
(660,)
(2640, 200)
ratio: 395.2
Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       657
          1       0.00      0.00      0.00         3

avg / total       0.99      1.00      0.99       660


Confusion matrix:
[[657   0]
 [  3   0]]


/Users/Edward_Chou/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
