In [2]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import numpy as np
import tensorflow as tf
import csv

from matplotlib.image import imread
import matplotlib.pyplot as plt
from sklearn import svm, metrics


In [10]:
import csv

with open("pac_guide.csv") as file:
    reader = csv.reader(file)
    i = 0
    image_paths = []
    camera_nums = []
    im_labels = []
    
    for row in reader:
        index = row[0]
        camera_num = row[1]
        label = row[2]
        filename = row[3]
        image_paths.append(filename)
        camera_nums.append(camera_num)
        im_labels.append(label)

In [11]:
files = ['08', '11', '15']


In [12]:
file = files[0]

train_indices = np.load('pac_arrays/train_' + str(file) + '.npy')
test_indices = np.load('pac_arrays/test_' + str(file) + '.npy')

#PAC_cnn_pca_features_08
data_cnn_features = np.load("PAC_cnn_pca_features_" + str(file) + ".npy")
print(train_indices.shape)
print(test_indices.shape)
print(data_cnn_features.shape)

train_len = len(train_indices)
test_len = len(test_indices)
features_train = data_cnn_features[:train_len]
features_test = data_cnn_features[train_len:train_len+test_len]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]

num_0 = 0
num_1 = 1
for i in labels_train:
    if i == '0':
        num_0 += 1
    if i == '1':
        num_1 += 1
ratio = num_0 / num_1
print('ratio: ' + str(ratio))

class_weight = {'0' : 1.,
    '1': ratio}

classifier = svm.SVC(gamma=0.001, class_weight = class_weight)

classifier.fit(features_train, labels_train)

predictions = classifier.predict(features_test)

print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

(1980,)
(660,)
(2640, 256)
ratio: 8.213953488372093
Classification report:
             precision    recall  f1-score   support

          0       0.99      0.95      0.97       594
          1       0.70      0.94      0.80        66

avg / total       0.96      0.95      0.96       660


Confusion matrix:
[[567  27]
 [  4  62]]


In [13]:
file = files[1]

train_indices = np.load('pac_arrays/train_' + str(file) + '.npy')
test_indices = np.load('pac_arrays/test_' + str(file) + '.npy')

#PAC_cnn_pca_features_08
data_cnn_features = np.load("PAC_cnn_pca_features_" + str(file) + ".npy")
print(train_indices.shape)
print(test_indices.shape)
print(data_cnn_features.shape)

train_len = len(train_indices)
test_len = len(test_indices)
features_train = data_cnn_features[:train_len]
features_test = data_cnn_features[train_len:train_len+test_len]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]

num_0 = 0
num_1 = 1
for i in labels_train:
    if i == '0':
        num_0 += 1
    if i == '1':
        num_1 += 1
ratio = num_0 / num_1
print('ratio: ' + str(ratio))

class_weight = {'0' : 1.,
    '1': ratio}

classifier = svm.SVC(gamma=0.001, class_weight = class_weight)

classifier.fit(features_train, labels_train)

predictions = classifier.predict(features_test)

print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

(1980,)
(660,)
(2640, 256)
ratio: 19.214285714285715
Classification report:
             precision    recall  f1-score   support

          0       1.00      0.91      0.95       635
          1       0.29      0.92      0.45        25

avg / total       0.97      0.91      0.93       660


Confusion matrix:
[[580  55]
 [  2  23]]


In [14]:
file = files[2]

train_indices = np.load('pac_arrays/train_' + str(file) + '.npy')
test_indices = np.load('pac_arrays/test_' + str(file) + '.npy')

#PAC_cnn_pca_features_08
data_cnn_features = np.load("PAC_cnn_pca_features_" + str(file) + ".npy")
print(train_indices.shape)
print(test_indices.shape)
print(data_cnn_features.shape)

train_len = len(train_indices)
test_len = len(test_indices)
features_train = data_cnn_features[:train_len]
features_test = data_cnn_features[train_len:train_len+test_len]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]

num_0 = 0
num_1 = 1
for i in labels_train:
    if i == '0':
        num_0 += 1
    if i == '1':
        num_1 += 1
ratio = num_0 / num_1
print('ratio: ' + str(ratio))

class_weight = {'0' : 1.,
    '1': ratio}

classifier = svm.SVC(gamma=0.001, class_weight = class_weight)

classifier.fit(features_train, labels_train)

predictions = classifier.predict(features_test)

print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

(1980,)
(660,)
(2640, 256)
ratio: 395.2
Classification report:
             precision    recall  f1-score   support

          0       1.00      0.92      0.96       657
          1       0.05      1.00      0.10         3

avg / total       1.00      0.92      0.95       660


Confusion matrix:
[[602  55]
 [  0   3]]
