In [1]:
import csv
import math

import matplotlib.pyplot as plt
import numpy as np

from keras.models import load_model
import cv2
from skimage.transform import resize
from keras.preprocessing import image




Using TensorFlow backend.


In [2]:
import csv

with open("pac_transform_guide.csv") as file:
    reader = csv.reader(file)
    i = 0
    image_paths = []
    sanitation_labels = []
    
    for ind, row in enumerate(reader):
        index = row[0]
        filename = row[1]
        label = row[2]
        image_paths.append(filename)
        sanitation_labels.append(label)

In [3]:
camera_num = '08'

new_model = load_model('/pac_models/pca_augment_camera_' + camera_num + '.hdf5')
test_indices = np.load('pac_augment_arrays/ocean_train_inds_' + camera_num + '.npy')

true_label = []
predicted_label = []
for index in test_indices:
    sanit_label = sanitation_labels[index]
    true_label.append(str(sanit_label))
    
    #data = np.load(image_paths[int(index)])
    #depth_map = data['x'].astype(np.float32)
    #orig_img, ocean = depth_map_to_image(depth_map)
    #img = resize(ocean, (224, 224), mode='constant')
    path =  image_paths[index]
    img = image.load_img(path, target_size=(224, 224))
    data = np.expand_dims(image.img_to_array(img), axis=0)
    
    # Prediction outputs softmax vector
    prediction = new_model.predict(data)
    
    # Set most confident prediction as label, and convert it to our price scale
    label = np.argmax(prediction)
    #print(label)
    if label == 0:  
        predicted_label.append('0')
    if label == 1:  
        predicted_label.append('1')

In [4]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification report:\n%s\n"
      % (classification_report(true_label, predicted_label)))
print("Confusion matrix:\n%s" % confusion_matrix(true_label, predicted_label))

Classification report:
             precision    recall  f1-score   support

          0       1.00      0.98      0.99      1766
          1       0.89      0.98      0.93       214

avg / total       0.99      0.98      0.98      1980


Confusion matrix:
[[1739   27]
 [   4  210]]


In [5]:
camera_num = '11'

new_model = load_model('/pac_models/pca_augment_camera_' + camera_num + '.hdf5')
test_indices = np.load('pac_augment_arrays/ocean_train_inds_' + camera_num + '.npy')

true_label = []
predicted_label = []
for index in test_indices:
    sanit_label = sanitation_labels[index]
    true_label.append(str(sanit_label))
    
    #data = np.load(image_paths[int(index)])
    #depth_map = data['x'].astype(np.float32)
    #orig_img, ocean = depth_map_to_image(depth_map)
    #img = resize(ocean, (224, 224), mode='constant')
    path =  image_paths[index]
    img = image.load_img(path, target_size=(224, 224))
    data = np.expand_dims(image.img_to_array(img), axis=0)
    
    # Prediction outputs softmax vector
    prediction = new_model.predict(data)
    
    # Set most confident prediction as label, and convert it to our price scale
    label = np.argmax(prediction)
    #print(label)
    if label == 0:  
        predicted_label.append('0')
    if label == 1:  
        predicted_label.append('1')

In [6]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification report:\n%s\n"
      % (classification_report(true_label, predicted_label)))
print("Confusion matrix:\n%s" % confusion_matrix(true_label, predicted_label))

Classification report:
             precision    recall  f1-score   support

          0       1.00      0.98      0.99      1883
          1       0.67      0.97      0.79        97

avg / total       0.98      0.98      0.98      1980


Confusion matrix:
[[1837   46]
 [   3   94]]


In [7]:
camera_num = '15'

new_model = load_model('/pac_models/pca_augment_camera_' + camera_num + '.hdf5')
test_indices = np.load('pac_augment_arrays/ocean_train_inds_' + camera_num + '.npy')

true_label = []
predicted_label = []
for index in test_indices:
    sanit_label = sanitation_labels[index]
    true_label.append(str(sanit_label))
    
    #data = np.load(image_paths[int(index)])
    #depth_map = data['x'].astype(np.float32)
    #orig_img, ocean = depth_map_to_image(depth_map)
    #img = resize(ocean, (224, 224), mode='constant')
    path =  image_paths[index]
    img = image.load_img(path, target_size=(224, 224))
    data = np.expand_dims(image.img_to_array(img), axis=0)
    
    # Prediction outputs softmax vector
    prediction = new_model.predict(data)
    
    # Set most confident prediction as label, and convert it to our price scale
    label = np.argmax(prediction)
    #print(label)
    if label == 0:  
        predicted_label.append('0')
    if label == 1:  
        predicted_label.append('1')

In [8]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification report:\n%s\n"
      % (classification_report(true_label, predicted_label)))
print("Confusion matrix:\n%s" % confusion_matrix(true_label, predicted_label))

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1976
          1       1.00      0.25      0.40         4

avg / total       1.00      1.00      1.00      1980


Confusion matrix:
[[1976    0]
 [   3    1]]
