In [1]:
import csv
import math

import matplotlib.pyplot as plt
import numpy as np

from keras.models import load_model
import cv2
from skimage.transform import resize
from keras.preprocessing import image




Using TensorFlow backend.


In [2]:
with open("pac_guide.csv") as file:
    reader = csv.reader(file)
    i = 0
    image_paths = []
    camera_nums = []
    sanitation_labels = []
    
    for row in reader:
        index = row[0]
        camera_num = row[1]
        label = row[2]
        filename = row[3]
        image_paths.append(filename)
        #camera_nums.append(camera_num)
        sanitation_labels.append(label)

In [3]:
def depth_map_to_image(depth_map):
    img = cv2.normalize(depth_map, depth_map, 0, 1, cv2.NORM_MINMAX)
    img = np.array(img * 255, dtype=np.uint8)
    orig_img = img
    img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
    img = cv2.applyColorMap(img, cv2.COLORMAP_OCEAN)
    #img = resize(img, 224, 224)

    return orig_img, img

In [12]:
camera_num = '08'

new_model = load_model('/pac_models/pca_camera_' + camera_num + '.hdf5')
test_indices = np.load('pac_arrays/train_' + camera_num + '.npy')

true_label = []
predicted_label = []
for index in test_indices:
    sanit_label = sanitation_labels[index]
    true_label.append(str(sanit_label))
    
    data = np.load(image_paths[int(index)])
    depth_map = data['x'].astype(np.float32)
    orig_img, ocean = depth_map_to_image(depth_map)
    img = resize(ocean, (224, 224), mode='constant')
    #img = image.load_img(path, target_size=(224, 224))
    data = np.expand_dims(image.img_to_array(img), axis=0)
    
    # Prediction outputs softmax vector
    prediction = new_model.predict(data)
    
    # Set most confident prediction as label, and convert it to our price scale
    label = np.argmax(prediction)
    #print(label)
    if label == 0:  
        predicted_label.append('0')
    if label == 1:  
        predicted_label.append('1')

In [13]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification report:\n%s\n"
      % (classification_report(true_label, predicted_label)))
print("Confusion matrix:\n%s" % confusion_matrix(true_label, predicted_label))

Classification report:
             precision    recall  f1-score   support

          0       0.89      1.00      0.94      1766
          1       0.00      0.00      0.00       214

avg / total       0.80      0.89      0.84      1980


Confusion matrix:
[[1766    0]
 [ 214    0]]


/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
camera_num = '11'

new_model = load_model('/pac_models/pca_camera_' + camera_num + '.hdf5')
test_indices = np.load('pac_arrays/train_' + camera_num + '.npy')

true_label = []
predicted_label = []
for index in test_indices:
    sanit_label = sanitation_labels[index]
    true_label.append(str(sanit_label))
    
    data = np.load(image_paths[int(index)])
    depth_map = data['x'].astype(np.float32)
    orig_img, ocean = depth_map_to_image(depth_map)
    img = resize(ocean, (224, 224), mode='constant')
    #img = image.load_img(path, target_size=(224, 224))
    data = np.expand_dims(image.img_to_array(img), axis=0)
    
    # Prediction outputs softmax vector
    prediction = new_model.predict(data)
    
    # Set most confident prediction as label, and convert it to our price scale
    label = np.argmax(prediction)
    #print(label)
    if label == 0:  
        predicted_label.append('0')
    if label == 1:  
        predicted_label.append('1')

In [15]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification report:\n%s\n"
      % (classification_report(true_label, predicted_label)))
print("Confusion matrix:\n%s" % confusion_matrix(true_label, predicted_label))

Classification report:
             precision    recall  f1-score   support

          0       0.95      1.00      0.97      1883
          1       0.00      0.00      0.00        97

avg / total       0.90      0.95      0.93      1980


Confusion matrix:
[[1883    0]
 [  97    0]]


/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
camera_num = '15'

new_model = load_model('/pac_models/pca_camera_' + camera_num + '.hdf5')
test_indices = np.load('pac_arrays/train_' + camera_num + '.npy')

true_label = []
predicted_label = []
for index in test_indices:
    sanit_label = sanitation_labels[index]
    true_label.append(str(sanit_label))
    
    data = np.load(image_paths[int(index)])
    depth_map = data['x'].astype(np.float32)
    orig_img, ocean = depth_map_to_image(depth_map)
    img = resize(ocean, (224, 224), mode='constant')
    #img = image.load_img(path, target_size=(224, 224))
    data = np.expand_dims(image.img_to_array(img), axis=0)
    
    # Prediction outputs softmax vector
    prediction = new_model.predict(data)
    
    # Set most confident prediction as label, and convert it to our price scale
    label = np.argmax(prediction)
    #print(label)
    if label == 0:  
        predicted_label.append('0')
    if label == 1:  
        predicted_label.append('1')

In [17]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification report:\n%s\n"
      % (classification_report(true_label, predicted_label)))
print("Confusion matrix:\n%s" % confusion_matrix(true_label, predicted_label))

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1976
          1       0.00      0.00      0.00         4

avg / total       1.00      1.00      1.00      1980


Confusion matrix:
[[1976    0]
 [   4    0]]


/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
